//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Task.Data
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Task1Entities : DbContext
    {
        public Task1Entities()
            : base("name=Task1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Mas_City> Mas_City { get; set; }
        public virtual DbSet<Mas_Country> Mas_Country { get; set; }
        public virtual DbSet<Mas_State> Mas_State { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
    }
}
